export interface AiDetectionResult {
  isAiAssisted: boolean;
  markers: string[];
  confidence: "high" | "medium" | "low";
}

const CO_AUTHOR_PATTERNS = [
  /co-authored-by:.*copilot/i,
  /co-authored-by:.*claude/i,
  /co-authored-by:.*cursor/i,
  /co-authored-by:.*\bai\b/i,
  /co-authored-by:.*github.*actions/i,
  /co-authored-by:.*noreply@anthropic/i,
];

const COMMIT_MSG_PATTERNS = [
  /generated by/i,
  /auto-generated/i,
  /\[ai\]/i,
  /🤖\s*(generated|created|built)/i,
  /copilot.*generated/i,
  /cursor.*generated/i,
];

const PR_BODY_PATTERNS = [
  /generated with.*claude/i,
  /generated with.*copilot/i,
  /generated with.*cursor/i,
  /ai-assisted/i,
  /ai.generated/i,
  /\[ai\]/i,
];

const AI_CONFIG_FILES = [
  ".copilot",
  ".github/copilot-instructions.md",
  ".cursor/",
  ".cursorrules",
  "CLAUDE.md",
  ".claude/",
];

export function detectAiMarkers(data: {
  commitMessages: string[];
  prBody: string;
  changedFiles: string[];
  linesAdded: number;
  commitCount: number;
  authoredDurationMinutes?: number;
}): AiDetectionResult {
  const markers: string[] = [];

  for (const msg of data.commitMessages) {
    for (const pattern of CO_AUTHOR_PATTERNS) {
      if (pattern.test(msg)) {
        markers.push(`co-author: ${msg.match(pattern)?.[0]}`);
      }
    }
    for (const pattern of COMMIT_MSG_PATTERNS) {
      if (pattern.test(msg)) {
        markers.push(`commit-msg: ${pattern.source}`);
      }
    }
  }

  for (const pattern of PR_BODY_PATTERNS) {
    if (pattern.test(data.prBody)) {
      markers.push(`pr-body: ${pattern.source}`);
    }
  }

  for (const file of data.changedFiles) {
    for (const configFile of AI_CONFIG_FILES) {
      if (file.includes(configFile)) {
        markers.push(`ai-config: ${configFile}`);
      }
    }
  }

  if (
    data.linesAdded > 500 &&
    data.commitCount <= 2 &&
    data.authoredDurationMinutes !== undefined &&
    data.authoredDurationMinutes < 30
  ) {
    markers.push("heuristic: large-fast-pr");
  }

  const uniqueMarkers = [...new Set(markers)];
  let confidence: AiDetectionResult["confidence"] = "low";
  if (uniqueMarkers.some((m) => m.startsWith("co-author:"))) {
    confidence = "high";
  } else if (uniqueMarkers.length >= 2) {
    confidence = "medium";
  } else if (uniqueMarkers.length === 1) {
    confidence = "low";
  }

  return {
    isAiAssisted: uniqueMarkers.length > 0,
    markers: uniqueMarkers,
    confidence,
  };
}
